### ISSUE TITLE
Lots of input lag

### ISSUE THREAD

**Issue by sequoyahfrc** [sequoyahfrc/GoBabyGo#1]
Motors have lots of lag when using the joystick

**Comment by brent-hollers** [comment]
This is the current issue to fix:

1. Simplify code and use global variables for values
2. Transmit raw value and interpret (L, R and 0-1023) in receiver file
3. Scale value before transmission, add motor designation

Do each of these in order with testing on physical device before commits and should be done as a separate branch (put in branch V2.0

- [ ] Simplify code and use global variables for values

- [ ] Transmit raw value and interpret (L, R and 0-1023) in receiver file

- [ ] Scale value before transmission, add motor designation
